[ftp]
crash_reports = "atmosphere/crash_reports"
runtime = "totksavs"

# Mod files
[[ftp.file]]
local = "build-DDEBUG/totksavs.nso"
target = "atmosphere/contents/0100F2C011586000/exefs/subsdk9"

[[ftp.file]]
local = "build-DDEBUG/app.npdm"
target = "atmosphere/contents/0100F2C011586000/exefs/main.npdm"

[ips]
mod_offset = "0x3483000" # this is used for address conversion for branching

[ips.main100]
id = "082CE09B06E33A123CB1E2770F5F9147"
offset = "0"

# Runtime placeholder/version files
[[ftp.file]]
local = "build-DDEBUG/DebugVersion.txt"
target = "totksavs/main.log"

[[ftp.file]]
local = "build-DDEBUG/DebugVersion.txt"
target = "totksavs/latest.txt"

[[ftp.file]]
local = "build-DDEBUG/DebugVersion.txt"
target = "atmosphere/contents/0100F2C011586000/romfs/System/Version.txt"
